# Generated by Django 3.1.1 on 2021-04-24 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlogic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='unique_code',
            field=models.SlugField(max_length=12, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='teacher_code',
            field=models.SlugField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='organization',
            name='unique_code',
            field=models.SlugField(max_length=10, unique=True),
        ),
    ]
