# Generated by Django 3.1.1 on 2021-04-24 14:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainlogic', '0004_auto_20210424_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='present_students',
            field=models.ManyToManyField(blank=True, related_name='PresentStudents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='Students', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='organization',
            name='teachers',
            field=models.ManyToManyField(blank=True, related_name='Teachers', to=settings.AUTH_USER_MODEL),
        ),
    ]
