# Generated by Django 3.1.1 on 2021-05-21 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlogic', '0007_auto_20210425_2210'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='verify/faces')),
                ('orgcode', models.SlugField(max_length=10, unique=True)),
                ('classcode', models.SlugField(max_length=10, unique=True)),
            ],
        ),
    ]
