# Generated by Django 3.1.1 on 2021-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlogic', '0008_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='verification',
            name='classcode',
            field=models.SlugField(max_length=10),
        ),
        migrations.AlterField(
            model_name='verification',
            name='orgcode',
            field=models.SlugField(max_length=10),
        ),
    ]
