# Generated by Django 3.1.1 on 2021-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainlogic', '0005_auto_20210424_2018'),
        ('accounts', '0002_auto_20210423_0733'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='joined_organizations',
            field=models.ManyToManyField(blank=True, null=True, to='mainlogic.Organization'),
        ),
    ]
